##  Facter Rakefile
##
##  Author:         Nate St. Germain
##  Modified from:  Gary Larizza
##  License:        Apache
##  Created:        9/30/11
##  Last Modified:  9/30/11
##
##  Description:
##
##  This module will create a package based on the Facter source. The facter
##  sourcefile is downloaded, expanded, and then copied into the Package's 
##  root directory.  The customize method sets all the initial variable values
##  that are needed for this module, and the pack method provides all the code 
##  to copy and set permissions on all the files that need to be installed.
##  You need to run this rakefile AS ROOT due to root:wheel permissions.
##
##
##  Overriding Facter Version:
##
##  We allow you to specify the version of Facter you want to build from the 
##  command line by doing the following:  'sudo PACKAGE_VERSION=1.6.0 rake pkg'
##  Running that from the command line will tell this module to use version 
##  1.6.0 of Facter instead of the version specified in the Module. The 
##  pattern for this behavior can be found in the customize method (the if
##  statement checking ENV['PACKAGE_VERSION'])
##  
##
##  Creating your package:
##
##  Change to the directory containing this module and execute the following
##  commands to build the resultant file:
##
##  'sudo rake pkg'  ==>  Builds a Package
##  'sudo rake dmg'  ==>  Builds a DMG
##  'sudo rake zip'  ==>  Builds a Zip file
##

require 'pathname'
require 'fileutils'
require 'find'
require "#{Pathname.pwd.parent.parent}/cart"

task :default => :pkg
raise "\n==========\nThis Rakefile must run as root\nRun \"sudo rake <task>\"\n==========" unless Process.uid == 0

# Any variables that need to be changed should be done inside the customize
# method
def customize
  # If the PACKAGE_VERSION variable is passed from the command line, then set
  # @package_version equal to what was passed. Else, use the current version
  # of facter
  if ENV['PACKAGE_VERSION']
    @package_version = ENV['PACKAGE_VERSION']
  else
    @package_version        = '1.6.1'
  end
  
  # Facter-specific Variables
  @title                  = "Facter_Install"
  @reverse_domain         = "com.puppetlabs"
  @package_major_version  = @package_version.split('.')[0]
  @package_minor_version  = @package_version.split('.')[1] + @package_version.split('.')[2]
  @facter_file            = "facter-#{@package_version}"
  @facter_url             = "http://downloads.puppetlabs.com/facter/"
  @facter_tarfile         = "#{@facter_file}.tar.gz"
end

# The pack method is for adding files to the package's payload. Note that
# @working_tree['WORK_D'] is the path to the working directory. All files
# installed into this directory will be copied into the package's payload.
def pack
  # Set the variable here so it can grab the contents of @working_tree (which
  # is set in the make_directory_tree method).
  @work = "#{@working_tree['WORK_D']}"
  
  # Download and unpack the Facter Source
  safe_system("curl #{@facter_url}/#{@facter_tarfile} -o #{@facter_tarfile}")
  safe_system("#{TAR} xzf #{@facter_tarfile}")
  
  # Make all necessary directories
  FileUtils.mkdir_p("#{@work}/usr/bin")
  FileUtils.mkdir_p("#{@work}/Library/Ruby/Site/1.8/facter")
  
  # Install necessary files
  safe_system("#{DITTO} -V ./#{@facter_file}/bin/ #{@work}/usr/bin")
  safe_system("#{DITTO} -V ./#{@facter_file}/lib/ #{@work}/Library/Ruby/Site/1.8/")
  
  # Setup a preflight script and replace variables in the files with 
  # the correct paths.
  safe_system("#{INSTALL} -o root -g wheel -m 644 ./#{@facter_file}/conf/osx/preflight #{@working_tree['SCRIPT_D']}")
  safe_system("sed -i '' \"s\#{SITELIBDIR}\#/usr/lib/ruby/site_ruby/1.8\#g\" #{@working_tree['SCRIPT_D']}/preflight")
  safe_system("sed -i '' \"s\#{BINDIR}\#/usr/bin\#g\" #{@working_tree['SCRIPT_D']}/preflight")

  # Set Permissions
  FileUtils.chmod_R(0755, "#{@work}/usr/bin")
  FileUtils.chown_R('root', 'wheel', "#{@work}/usr/bin")
  FileUtils.chmod_R(0644, "#{@work}/Library/Ruby/Site/1.8/")
  FileUtils.chown_R('root', 'wheel', "#{@work}/Library/Ruby/Site/1.8/")
  Find.find("#{@work}/Library/Ruby/Site/1.8/") do |dir|
    FileUtils.chmod(0755, dir) if File.directory?(dir)
  end
end


### Nothing Below this line should need to be modified ###


desc "This task will create an Apple .pkg file"
task :pkg do
  customize
  make_directory_tree
  pack
  output_file
  build_package
  copy_to_local_dir(@package_file)
  announce("Your package #{@package_file} has been built!")
end

desc "This task will create an Apple .pkg encapsulated into a .dmg file"
task :dmg do
  customize
  make_directory_tree
  pack
  output_file
  build_dmg
  announce("Your DMG #{@dmg_file} has been built!")
end

desc "This task will create a .zip file with your package in it."
task :zip do
  customize
  make_directory_tree
  pack
  output_file
  build_zip
  announce("Your Zip file #{@zip_file} has been built!")
end
